name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-mpich:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: install dependencies
      run: |
        ./maint/install-autotools.sh $GITHUB_WORKSPACE/autotools
        ./maint/install-mpi.sh $GITHUB_WORKSPACE mpich_shm
    - name: autogen
      run: |
        export PATH=$GITHUB_WORKSPACE/autotools/bin:$PATH
        ./autogen.sh
    - name: configure
      run: |
        export PATH=$GITHUB_WORKSPACE/mpich/bin:$PATH
        ./configure CC=mpicc CXX=mpicxx --prefix=$PWD/i || cat config.log
    - name: make
      run: |
        export PATH=$GITHUB_WORKSPACE/mpich/bin:$PATH
        make -j
    - name: make install
      run: make install
  build-openmpi:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: install dependencies
      run: |
        ./maint/install-autotools.sh $GITHUB_WORKSPACE/autotools
        ./maint/install-mpi.sh $GITHUB_WORKSPACE openmpi
    - name: autogen
      run: |
        export PATH=$GITHUB_WORKSPACE/autotools/bin:$PATH
        ./autogen.sh
    - name: configure
      run: |
        export PATH=$GITHUB_WORKSPACE/open-mpi/bin:$PATH
        ./configure CC=mpicc CXX=mpicxx --prefix=$PWD/i
    - name: make
      run: |
        export PATH=$GITHUB_WORKSPACE/open-mpi/bin:$PATH
        make -j
    - name: make install
      run: make install
